[package]
name = "new-drug-reimbursement-game"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
uogto-game-core = { path = "../uogto-game-core" }
uogto-game-solve = { path = "../uogto-game-solve" }

[lints]
workspace = true
